services:
  - type: web
    name: n8n
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: main # optional (defaults to master)
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PGHOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: PGPORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: PGUSER
        fromDatabase:
          name: n8n-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/
    disk:
      name: n8n-disk
      mountPath: /home/node/.n8n
      sizeGB: 2

databases:
  - name: n8n-db
    plan: starter # Modifié de basic-256mb à starter pour correspondre à la documentation
